blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/learninghub44/HOUSE-HANTING/discussions
    about: Please ask general questions in Discussions rather than as an issue.
